# Generated by Django 3.2.8 on 2021-10-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact',
            new_name='contact_no',
        ),
    ]
