# Generated by Django 3.2.8 on 2021-10-12 18:49

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0002_rename_contact_company_contact_no'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
